version: "3.7"

services:
  data-book-elasticsearch:
    image: elasticsearch:8.18.0
    container_name: library_book_elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - local-network
    ulimits:
      memlock:
        hard: -1
        soft: -1
  data-book-redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - local-network
  library-book-api:
    image: docker.io/ntacarreao/library-book-api:0.0.4
    environment:
      - TESTHOSTELASTIC=http://data-book-elasticsearch:9200
    depends_on:
      - data-book-elasticsearch
      - data-book-redis
    ports:
      - "8080:8080"
    networks:
      - local-network
    links:
      - data-book-elasticsearch
volumes:
  es_data:
    driver: local

networks:
  local-network:
    driver: bridge