server:
  servlet:
    context-path: /library-book/api
  port: 8080
spring:
  application:
   name: library-book-api
  multipart:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    elasticsearch:
      repositories:
        enable: true
  elasticsearch:
      uris: ${HOST_ELASTICSEARCH:http://localhost:9200}
  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: INFO

open-library:
  url: "https://openlibrary.org"

cache:
  ttl:
    ms: 43200000